package com.real.shopping.dao;

import com.real.shopping.dataobject.UserRoleDO;
import org.springframework.cache.annotation.Cacheable;

import java.util.List;

public interface UserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    int insert(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    int insertSelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    UserRoleDO selectByPrimaryKey(Integer id);

    @Cacheable(value = "role",key = "'userId:'+#userId",unless = "#result==null")
    List<UserRoleDO> getRolesByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Mon Apr 08 15:12:39 CST 2019
     */
    int updateByPrimaryKey(UserRoleDO record);
}